theme: jekyll-theme-minimal
title: 刷题咖啡馆 
description: 
  <ul>
  <li>Website for coding cafe (<strong>cp stands for central perk</strong>)</li>
  <li>致力于用<strong>短视频</strong>展示题解</li>
  <li><a href="https://bit.ly/poirot_cafe">我的推理播客</a></li>
  </ul>
  
  # <img src="./assets/qr.jpeg" alt="qr" width="250" height="250">
