theme: jekyll-theme-minimal
title: 刷题咖啡馆 
description: 
  <ul>
  <li>Website for coding cafe (<strong>cp stands for central perk</strong>)</li>
  <li>致力于用<strong>短视频</strong>展示题解</li>
  </ul>

  <a href="https://dun.mianbaoduo.com/@sholmes" target="_blank"><img src="https://img.niucodata.com/dundunfan-bt.png"></a>

  <img src="./assets/qr.jpeg" alt="qr" width="250" height="250">
  # <img src="https://user-images.githubusercontent.com/106009933/184610387-41981da6-2c7f-40e7-831a-14fea0000dcf.jpeg" alt="qr" width="250" height="250">
